export const UPLOAD_START = "UPLOAD_START";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAILURE = "UPLOAD_FAILURE";

export const UPDATE_START = "UPDATE_START";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_FAILURE = "UPDATE_FAILURE";

export const CREATE_START = "CREATE_START";
export const CREATE_SUCCESS = "CREATE_SUCCESS";
export const CREATE_FAILURE = "CREATE_FAILURE";

export const DELETE_SUCCESS = "DELETE_SUCCESS";

export const RETREIVING_START = "RETREIVING_START";
export const RETREIVING_SUCCESS = "RETREIVING_SUCCESS";
export const RETREIVING_FAILURE = "RETREIVING_FAILURE";