export const UPLOAD_START = "UPLOAD_START";
export const UPLOAD_SUCCESS = "UPLOAD_SUCCESS";
export const UPLOAD_FAILURE = "UPLOAD_FAILURE";

export const RETREIVING_START = "RETREIVING_START";
export const RETREIVING_SUCCESS = "RETREIVING_SUCCESS";
export const RETREIVING_FAILURE = "RETREIVING_FAILURE";